# These settings are synced to GitHub by https://github.com/Marfeel/settings/
repository:
  description: __ProjectName__ repository
  topics: __TOPICS__
  private: true
  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: true
teams:
  - name: Systems
    permission: admin
  - name: Alice
    permission: admin
  - name: Marfeel-tech
    permission: push
branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      required_linear_history: true
      restrictions: null
